MeritPay.Web/Controllers/ImportDataController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MeritPay.Core.DTOs;
using MeritPay.Core.UseCases.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OfficeOpenXml;

namespace MeritPay.Web.Controllers
{
    public class ImportDataController : BaseController
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IImportDataService _importDataService;
        private readonly ILogger _logger;

        public ImportDataController(IWebHostEnvironment hostingEnvironment, ILogger<HomeController> logger, IImportDataService importData)
        {
            _hostingEnvironment = hostingEnvironment;
            _importDataService = importData;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        private async Task<List<string>> ReadExcel(IFormFile formFile)
        {
            List<string> errorList = new List<string>();
            var list = new List<ImportDataInputVM>();
            using (var stream = new MemoryStream())
            {
                await formFile.CopyToAsync(stream);
                using var package = new ExcelPackage(stream);
                ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
                var rowCount = worksheet.Dimension.Rows;

                for (int row = 3; row <= rowCount; row++)
                {
                    try
                    {
                        list.Add(new ImportDataInputVM
                        {
                            PersonCode = worksheet.Cells[row, 1].Value != null ? int.Parse(worksheet.Cells[row, 1].Value.ToString().Trim()) : 0,
                            BranchCode = worksheet.Cells[row, 4].Value != null ? int.Parse(worksheet.Cells[row, 4].Value.ToString().Trim()) : 0,

                            TaScore = worksheet.Cells[row, 6].Value != null ? int.Parse(worksheet.Cells[row, 6].Value.ToString().Trim()) : 0,
                            TaRankInBranch = worksheet.Cells[row, 7].Value != null ? int.Parse(worksheet.Cells[row, 7].Value.ToString().Trim()) : 0,
                            TaRankInZone = worksheet.Cells[row, 8].Value != null ? int.Parse(worksheet.Cells[row, 8].Value.ToString().Trim()) : 0,
                            TaRankInBank = worksheet.Cells[row, 9].Value != null ? int.Parse(worksheet.Cells[row, 9].Value.ToString().Trim()) : 0,

                            GroupScore = worksheet.Cells[row, 10].Value != null ? int.Parse(worksheet.Cells[row, 10].Value.ToString().Trim()) : 0,
                            GroupRankInBranch = worksheet.Cells[row, 11].Value != null ? int.Parse(worksheet.Cells[row, 11].Value.ToString().Trim()) : 0,
                            GroupRankInZone = worksheet.Cells[row, 12].Value != null ? int.Parse(worksheet.Cells[row, 12].Value.ToString().Trim()) : 0,
                            GroupRankInBank = worksheet.Cells[row, 13].Value != null ? int.Parse(worksheet.Cells[row, 13].Value.ToString().Trim()) : 0,

                            ArzeshScore = worksheet.Cells[row, 14].Value != null ? int.Parse(worksheet.Cells[row, 14].Value.ToString().Trim()) : 0,
                            ArzeshRankInBranch = worksheet.Cells[row, 15].Value != null ? int.Parse(worksheet.Cells[row, 15].Value.ToString().Trim()) : 0,
                            ArzeshRankInZone = worksheet.Cells[row, 16].Value != null ? int.Parse(worksheet.Cells[row, 16].Value.ToString().Trim()) : 0,
                            ArzeshRankInBank = worksheet.Cells[row, 17].Value != null ? int.Parse(worksheet.Cells[row, 17].Value.ToString().Trim()) : 0,

                            TotalScore = worksheet.Cells[row, 18].Value != null ? int.Parse(worksheet.Cells[row, 18].Value.ToString().Trim()) : 0,
                            TotalRankInBranch = worksheet.Cells[row, 19].Value != null ? int.Parse(worksheet.Cells[row, 19].Value.ToString().Trim()) : 0,
                            TotalRankInZone = worksheet.Cells[row, 20].Value != null ? int.Parse(worksheet.Cells[row, 20].Value.ToString().Trim()) : 0,
                            TotalRankInBank = worksheet.Cells[row, 21].Value != null ? int.Parse(worksheet.Cells[row, 21].Value.ToString().Trim()) : 0,

                            TajhizManabeArzan = worksheet.Cells[row, 22].Value != null ? decimal.Parse(worksheet.Cells[row, 22].Value.ToString().Trim()) : 0,
                            TajhizManabeGeran = worksheet.Cells[row, 23].Value != null ? decimal.Parse(worksheet.Cells[row, 23].Value.ToString().Trim()) : 0,

                            TakhsisManabeTedadTashilat = worksheet.Cells[row, 24].Value != null ? int.Parse(worksheet.Cells[row, 24].Value.ToString().Trim()) : 0,
                            TakhsisManabeMablaghTashilat = worksheet.Cells[row, 25].Value != null ? decimal.Parse(worksheet.Cells[row, 25].Value.ToString().Trim()) : 0,
                            TakhsisManabeTedadZSemanat = worksheet.Cells[row, 26].Value != null ? int.Parse(worksheet.Cells[row, 26].Value.ToString().Trim()) : 0,
                            TakhsisManabeMablaghZemanat = worksheet.Cells[row, 27].Value != null ? decimal.Parse(worksheet.Cells[row, 27].Value.ToString().Trim()) : 0,
                            TakhsisManabeEtebaratAsnadi = worksheet.Cells[row, 28].Value != null ? decimal.Parse(worksheet.Cells[row, 28].Value.ToString().Trim()) : 0,

                            DaramadKarmozdi = worksheet.Cells[row, 29].Value != null ? int.Parse(worksheet.Cells[row, 29].Value.ToString().Trim()) : 0,

                            BankdariElectronicKartHadiye = worksheet.Cells[row, 30].Value != null ? int.Parse(worksheet.Cells[row, 30].Value.ToString().Trim()) : 0,
                            BankdariElectronicIranKart = worksheet.Cells[row, 31].Value != null ? int.Parse(worksheet.Cells[row, 31].Value.ToString().Trim()) : 0,
                            BankdariElectronicKilid = worksheet.Cells[row, 32].Value != null ? int.Parse(worksheet.Cells[row, 32].Value.ToString().Trim()) : 0,

                            SayerAsnadNaghdiVaGheirNaghdi = worksheet.Cells[row, 33].Value != null ? int.Parse(worksheet.Cells[row, 33].Value.ToString().Trim()) : 0,
                            SayerAsnadBarghashti = worksheet.Cells[row, 34].Value != null ? int.Parse(worksheet.Cells[row, 34].Value.ToString().Trim()) : 0,
                            SayerTarifMoshtari = worksheet.Cells[row, 35].Value != null ? int.Parse(worksheet.Cells[row, 35].Value.ToString().Trim()) : 0,
                            SayerEftetahHesab = worksheet.Cells[row, 36].Value != null ? int.Parse(worksheet.Cells[row, 36].Value.ToString().Trim()) : 0,
                            SayerBakhshnameKhani = worksheet.Cells[row, 37].Value != null ? int.Parse(worksheet.Cells[row, 37].Value.ToString().Trim()) : 0,
                            SayerTakhirVaTajil = worksheet.Cells[row, 38].Value != null ? int.Parse(worksheet.Cells[row, 38].Value.ToString().Trim()) : 0,

                            ArzanRankInBranch = worksheet.Cells[row, 39].Value != null ? int.Parse(worksheet.Cells[row, 39].Value.ToString().Trim()) : 0,
                            ArzanRankInZone = worksheet.Cells[row, 40].Value != null ? int.Parse(worksheet.Cells[row, 40].Value.ToString().Trim()) : 0,
                            ArzanRankInBank = worksheet.Cells[row, 41].Value != null ? int.Parse(worksheet.Cells[row, 41].Value.ToString().Trim()) : 0,

                            GeranRankInBranch = worksheet.Cells[row, 42].Value != null ? int.Parse(worksheet.Cells[row, 42].Value.ToString().Trim()) : 0,
                            GeranRankInZone = worksheet.Cells[row, 43].Value != null ? int.Parse(worksheet.Cells[row, 43].Value.ToString().Trim()) : 0,
                            GeranRankInBank = worksheet.Cells[row, 44].Value != null ? int.Parse(worksheet.Cells[row, 44].Value.ToString().Trim()) : 0,

                            TedadTashilatRankInBranch = worksheet.Cells[row, 45].Value != null ? int.Parse(worksheet.Cells[row, 45].Value.ToString().Trim()) : 0,
                            TedadTashilatRankInZone = worksheet.Cells[row, 46].Value != null ? int.Parse(worksheet.Cells[row, 46].Value.ToString().Trim()) : 0,
                            TedadTashilatRankInBank = worksheet.Cells[row, 47].Value != null ? int.Parse(worksheet.Cells[row, 47].Value.ToString().Trim()) : 0,

                            MablaghTashilatRankInBranch = worksheet.Cells[row, 48].Value != null ? int.Parse(worksheet.Cells[row, 48].Value.ToString().Trim()) : 0,
                            MablaghTashilatRankInZone = worksheet.Cells[row, 49].Value != null ? int.Parse(worksheet.Cells[row, 49].Value.ToString().Trim()) : 0,
                            MablaghTashilatRankInBank = worksheet.Cells[row, 50].Value != null ? int.Parse(worksheet.Cells[row, 50].Value.ToString().Trim()) : 0,

                            TedadZemantRankInBranch = worksheet.Cells[row, 51].Value != null ? int.Parse(worksheet.Cells[row, 51].Value.ToString().Trim()) : 0,
                            TedadZemantRankInZone = worksheet.Cells[row, 52].Value != null ? int.Parse(worksheet.Cells[row, 52].Value.ToString().Trim()) : 0,
                            TedadZemantRankInBank = worksheet.Cells[row, 53].Value != null ? int.Parse(worksheet.Cells[row, 53].Value.ToString().Trim()) : 0,

                            MablaghZemantRankInBranch = worksheet.Cells[row, 54].Value != null ? int.Parse(worksheet.Cells[row, 54].Value.ToString().Trim()) : 0,
                            MablaghZemantRankInZone = worksheet.Cells[row, 55].Value != null ? int.Parse(worksheet.Cells[row, 55].Value.ToString().Trim()) : 0,
                            MablaghZemantRankInBank = worksheet.Cells[row, 56].Value != null ? int.Parse(worksheet.Cells[row, 56].Value.ToString().Trim()) : 0,

MeritPay.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MeritPay.Core.DTOs;
using MeritPay.Core.Entities;
using MeritPay.Core.UseCases.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace MeritPay.Web.Controllers
{
    public class ReportController : BaseController
    {
        private readonly IReportService _reportService;
        private readonly IPersonArzeshyabiService _personArzeshyabiService;
        private readonly IPersonScoreService _personScoreService;
        private readonly IMeritPayFactorService _meritPayFactorService;
        private readonly ILogger _logger;
        private readonly IMapper _mapper;

        public ReportController(ILogger<HomeController> logger, IPersonArzeshyabiService personArzeshyabiService, IPersonScoreService personScoreService,
            IReportService reportService, IMeritPayFactorService meritPayFactorService, IMapper mapper)
        {
            _logger = logger;
            _reportService = reportService;
            _personArzeshyabiService = personArzeshyabiService;
            _personScoreService = personScoreService;
            _meritPayFactorService = meritPayFactorService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<ReportDataOutput> GetReportData()
        {
            try
            {
                int periodId = 1;

                _logger.LogInformation("اجرای متد بازیابی اطلاعات کارنامه");
                var personData = await _personArzeshyabiService.GetPersonArzeshyabiByPersonCodeAsync(periodId, 13137);
                //var result = _mapper.Map<Person, ReportDataVM>(personData);
                ReportDataVM dataVM = new ReportDataVM();
                dataVM.PersonCode = personData.PersonInBranch.Person.PersonCode;
                dataVM.FirstName = personData.PersonInBranch.Person.FirstName;
                dataVM.LastName = personData.PersonInBranch.Person.LastName;
                dataVM.BirthDate = personData.PersonInBranch.Person.BirthDate;
                dataVM.EmployeeDate = personData.PersonInBranch.Person.EmployeeDate;
                dataVM.StudyBranch = personData.PersonInBranch.Person.StudyBranch;
                dataVM.StudyJob = personData.PersonInBranch.Person.StudyJob;
                dataVM.Grade = personData.PersonInBranch.Person.Grade;
                dataVM.BranchCode = personData.PersonInBranch.Branch.BranchCode;
                dataVM.BranchName = personData.PersonInBranch.Branch.BranchName;
                dataVM.ZoneName = personData.PersonInBranch.Branch.ZoneName;
                dataVM.Arzyab1 = personData.Arzyab1.ToString();
                dataVM.Arzyab2 = personData.Arzyab2.ToString();
                dataVM.MaghtaArzeshyabi = personData.ArzyabiDate;

                var reportTaData = await _personScoreService.GetPersonScoreByPersonCodeAsync(periodId, personData.PersonInBranch.Person.PersonCode);
                List<ReportTaDataVM> listTa = new List<ReportTaDataVM>();
                foreach (var item in reportTaData)
                {
                    ReportTaDataVM ta = new ReportTaDataVM();
                    ta.ScoreIndexTitle = item.ScoreSubIndex.ScoreIndex.Title;
                    ta.ScoreSubIndexTitle = item.ScoreSubIndex.Title;
                    ta.Value = item.Value;
                    ta.Score = item.Score;
                    ta.RankInBranch = item.RankInBranch;
                    ta.RankInZone = item.RankInZone;
                    ta.RankInBank = item.RankInBank;
                    listTa.Add(ta);
                }
                dataVM.ReportTaDataList = listTa;

                var reportData = await _reportService.GetReportByPersonCodeAsync(periodId, personData.PersonInBranch.Person.PersonCode);
                foreach (var item in reportData)
                {
                    var txt = await _meritPayFactorService.GetMeritPayByIdAsync(item.MeritPayFactorId);
                    switch (txt.Title)
                    {
                        case "تراکنش های عملکردی":
                            dataVM.TaScore = item.Score;
                            dataVM.TaRankInBranch = item.RankInBranch;
                            dataVM.TaRankInZone = item.RankInZone;
                            dataVM.TaRankInBank = item.RankInBank;
                            break;
                        case "امتیاز گروهی":
                            dataVM.GroupScore = item.Score;
                            dataVM.GroupRankInBranch = item.RankInBranch;
                            dataVM.GroupRankInZone = item.RankInZone;
                            dataVM.GroupRankInBank = item.RankInBank;
                            break;
                        case "ارزشیابی فردی":
                            dataVM.ArzeshScore = item.Score;
                            dataVM.ArzeshRankInBranch = item.RankInBranch;
                            dataVM.ArzeshRankInZone = item.RankInZone;
                            dataVM.ArzeshRankInBank = item.RankInBank;
                            break;
                        default:
                            break;
                    }

                }
                return new ReportDataOutput(true, dataVM);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "خطا در بازیابی اطلاعات کارنامه");
                return new ReportDataOutput(false, null, "خطا در بازیابی اطلاعات کارنامه");
            }
        }

    }
}

MeritPay.Web/Views/Shared/Footer.cshtml
<div class="footer">
    <p>کلیه حقوق این ســـامـانه برای بانــک آینـــده محفوظ است</p>
</div>

MeritPay.Web/Views/Shared/TopPanel.cshtml
<div>
    <div class="nav-bar">
        <ul class="user-nav">
            <li class="user-icon">@MeritPay.Core.Common.CommonHelper.CurrentUserShowLabel</li>
            <li class="date-icon">امروز : @Faranam.Utils.PersianDate.Today(true, false)</li>
            <li>
                <form method="get" style="float:left" action="@Url.Action("ExitProgram")">
                    <input type="submit" class="signout-icon" value="خروج" />
                </form>
            </li>
        </ul>
    </div>
    <div class="header">
        <div class="header-right">
            <span>ســامانه محــاسبه کــارانه</span>
            <div class="arm"></div>
        </div>
    </div>
    <div class="menu">
        <div class="home"><a href="http://bs.ba24.ir/"></a></div>
        <ul id="main-menu"></ul>
    </div>


</div>

MeritPay.Web/Views/Shared/_Layout.cshtml
@using MeritPay.Core.Contracts;
@{
    string _p(MeritPay.Core.Common.UserPermission p)
    {
        string result = string.Empty;
        if (!MeritPay.Core.Common.CommonHelper.CurrentUserHasPermission(p))
        {
            result = "cssClass: 'd-not', ";
        }
        return result;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" type="image/x-icon" href="@Url.Content("/favicon.ico")" />
    <link href="@Url.Content(AppSettings.resourceUrl + "Plugin/Kendo/Theme/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content(AppSettings.resourceUrl + "Plugin/Kendo/Theme/kendo.official.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content(AppSettings.resourceUrl + "Plugin/Kendo/Theme/kendo.rtl.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content(AppSettings.resourceUrl + "Plugin/Common/common.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content(AppSettings.themeUrl + "Style/style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content(AppSettings.resourceUrl + "Plugin/JQuery/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content(AppSettings.resourceUrl + "Plugin/JQuery/jquery-persian-calendar.js")" type="text/javascript"></script>
    <script src="@Url.Content(AppSettings.resourceUrl + "Plugin/Kendo/kendo.all.min.js")" type="text/javascript"></script>
    <script src="@Url.Content((AppSettings.resourceUrl + "Plugin/Kendo/kendo.extension.js?1"))" type="text/javascript"></script>
    <script src="@Url.Content((AppSettings.resourceUrl + "Plugin/Common/common.js"))" type="text/javascript"></script>
    <script src="@Url.Content(AppSettings.resourceUrl + "Plugin/JQuery/jquery.maskedinput.js")" type="text/javascript"></script>
    <script>

    $(function () {

        $("#main-menu").kendoMenu({
            dataSource: [
                { text: "داشبورد", url: '@AppSettings.portalPath' },
                { text: "کارنامه", url: '@Url.Action("Index", "Report")' },
                {
                    text: "تنظیمات",
                    items: [
                        { text: "بارگذاری فایل اکسل", url: '@Url.Action("Index", "ImportData")' },
                        { text: "مشتریان حقوقی", url: '@Url.Action("LegalIndex", "CreditMonitoring")' }
                    ]
                }
            ]
    });

    });
    </script>

    <script src="@Url.Content(AppSettings.themeUrl + "Scripts/scrollTop.js")" type="text/javascript"></script>

    <style>
        .iEButton {
            background: transparent url("~/Plugin/Kendo/Theme/textures/green.png") repeat-x scroll center top !important;
            border: 1px solid #ab401b !important;
        }

        .textarea {
            height: 70px;
            margin-right: -1px;
            width: 100%;
        }

        div[d-wrp] div[d-field].x1 .x1 {
            border-bottom: 1px solid #bbb;
        }

        .noWrap {
            white-space: nowrap;
        }

        .k-grid td {
            padding: .4em 0;
        }
    </style>
</head>
<body class="k-rtl">
    <partial name="TopPanel.cshtml">
        <span class="validation-msg"></span>
        <div class="fullHeight">
            @RenderBody()
            <img class="scrollToTop" />
        </div>
        <partial name="Footer.cshtml">
</body>
</html>